filebeat.inputs:
  # Backend logs
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/backend/*.log
    fields:
      service: backend
    fields_under_root: true
    multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after

  # Nginx logs
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/nginx/*.log
    fields:
      service: nginx
    fields_under_root: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: changeme  # replace with your secret

setup.kibana:
  host: "http://kibana:5601"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
