"""Add cascade delete for comments relationship

Revision ID: 23d23abfd345
Revises: 6b2ba4124d83
Create Date: 2025-04-22 04:55:25.771041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d23abfd345'
down_revision = '6b2ba4124d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_publication_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publication', ['publication_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_publication_id_fkey', 'publication', ['publication_id'], ['id'])

    # ### end Alembic commands ###
