"""empty message

Revision ID: 3fae06116c05
Revises: 6cf840a3c4a1
Create Date: 2025-04-20 22:53:42.412552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fae06116c05'
down_revision = '6cf840a3c4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_field_hint', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['field_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_field_hint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
