"""Add work_form to Publication

Revision ID: a1fe8eeb8772
Revises: 5eb3836ecb10
Create Date: 2025-05-04 14:56:04.899049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1fe8eeb8772'
down_revision = '5eb3836ecb10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_form', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('work_form')

    # ### end Alembic commands ###
