"""Change publication authors structure

Revision ID: 203a78069fea
Revises: 
Create Date: 2025-04-19 21:43:51.045771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203a78069fea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('authors')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors', sa.VARCHAR(length=200), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
