"""Replace number_volume_pages with volume, number, pages columns

Revision ID: 2a1a292e7d47
Revises: b8ff6c629331
Create Date: 2025-04-20 16:15:10.514818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1a292e7d47'
down_revision = 'b8ff6c629331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pages', sa.String(length=50), nullable=True))
        batch_op.drop_column('number_volume_pages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_volume_pages', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('pages')
        batch_op.drop_column('number')
        batch_op.drop_column('volume')

    # ### end Alembic commands ###
