"""empty message

Revision ID: 2b51823fa60b
Revises: 62e530606503
Create Date: 2025-03-03 22:58:33.665796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b51823fa60b'
down_revision = '62e530606503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('plan_entry_publicationId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publication', ['publication_id'], ['id'])
        batch_op.drop_column('publicationId')

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.drop_constraint('plan_entry_plan_id_fkey', type_='foreignkey')
        batch_op.drop_column('status')

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('user_id')