"""Add display_name_id to Publication

Revision ID: 2c364f1b2d23
Revises: abf026e6c052
Create Date: 2025-04-15 15:07:23.035724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c364f1b2d23'
down_revision = 'abf026e6c052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'publication_type_display_name', ['display_name_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('display_name_id')

    # ### end Alembic commands ###
