"""empty message

Revision ID: 3bd72e5bf46e
Revises: 3fae06116c05
Create Date: 2025-04-21 01:16:51.796749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd72e5bf46e'
down_revision = '3fae06116c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=5000),
               existing_nullable=False)
        batch_op.alter_column('file_url',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('publisher',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('publication_author', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_author', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.alter_column('publisher',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('file_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
