"""Add approved_at and returned_at to Plan

Revision ID: 430a9a0caef5
Revises: 9683f6f2e87c
Create Date: 2025-04-11 15:30:21.733699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430a9a0caef5'
down_revision = '9683f6f2e87c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('returned_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('returned_at')
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###
