"""Add returned_for_revision to Publication

Revision ID: 4cd30964bcde
Revises: 2d4211b11c69
Create Date: 2025-03-02 21:55:53.186562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd30964bcde'
down_revision = '2d4211b11c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned_for_revision', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('returned_for_revision')

    # ### end Alembic commands ###
