"""Add returned_at and return_comment to Publication

Revision ID: 56ca64638927
Revises: 5cb8466e3b2b
Create Date: 2025-03-23 18:23:24.465161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ca64638927'
down_revision = '5cb8466e3b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.drop_column('approved')

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('return_comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('return_comment')
        batch_op.drop_column('returned_at')

    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
