"""empty message

Revision ID: 62e530606503
Revises: bf39d1af4167
Create Date: 2025-03-03 22:53:17.680664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e530606503'
down_revision = 'bf39d1af4167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expectedCount', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fillType', sa.String(length=10), nullable=False))
        batch_op.drop_column('status')
        batch_op.drop_column('authors')
        batch_op.drop_column('type')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('authors', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('fillType')
        batch_op.drop_column('expectedCount')

    # ### end Alembic commands ###
