"""empty message

Revision ID: 6b2ba4124d83
Revises: 3bd72e5bf46e
Create Date: 2025-04-22 04:44:54.114672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2ba4124d83'
down_revision = '3bd72e5bf46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_action_history', schema=None) as batch_op:
        batch_op.drop_constraint('publication_action_history_publication_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publication', ['publication_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_action_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('publication_action_history_publication_id_fkey', 'publication', ['publication_id'], ['id'])

    # ### end Alembic commands ###
