"""Увеличена длина поля password_hash

Revision ID: 70face05e036
Revises: 2d2179bc0338
Create Date: 2025-02-18 17:48:24.143634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70face05e036'
down_revision = '2d2179bc0338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
