"""Add is_locked to PlanEntry

Revision ID: 8fa25025665f
Revises: edea0a8d2c39
Create Date: 2025-03-07 02:26:55.116880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa25025665f'
down_revision = 'edea0a8d2c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_locked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
