"""empty message

Revision ID: 94b27efeb5f7
Revises: ca3a6b25cab6
Create Date: 2025-04-22 05:41:29.329788

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '94b27efeb5f7'
down_revision = 'ca3a6b25cab6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Этап 1: Добавляем колонку, разрешая NULL временно
    op.add_column('plan', sa.Column('user_id', sa.Integer(), nullable=True))

    # Этап 2: Заполняем user_id для существующих записей (ВАЖНО: укажите правильный ID пользователя!)
    # Если вы уверены, что таблица plan пуста, эту строку можно закомментировать или удалить.
    # Если НЕ уверены, НУЖНО указать ID существующего пользователя (например, администратора)
    # вместо '1'. Если этого не сделать и таблица не пуста, следующий шаг снова вызовет ошибку.
    try:
        op.execute('UPDATE plan SET user_id = 1 WHERE user_id IS NULL') # <--- ИЗМЕНИТЕ '1' ПРИ НЕОБХОДИМОСТИ
        print("INFO: Existing rows in 'plan' table updated with default user_id=1.")
    except Exception as e:
        print(f"WARNING: Could not update existing rows in 'plan' table. Maybe table is empty or user ID 1 doesn't exist? Error: {e}")
        # Решайте, критична ли ошибка здесь. Если таблица должна быть пустой, можно проигнорировать.

    # Этап 3: Устанавливаем NOT NULL для колонки user_id
    op.alter_column('plan', 'user_id', nullable=False)

    # Этап 4: Создаем внешний ключ (лучше делать это вне batch_alter_table, если шаги разделены)
    op.create_foreign_key(
        'fk_plan_user_id', # Даем явное имя ограничению
        'plan', 'user',
        ['user_id'], ['id'],
        ondelete='CASCADE' # Используйте ondelete='CASCADE' как было задумано, или другое правило
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Порядок действий в downgrade обратный

    # Удаляем внешний ключ
    op.drop_constraint('fk_plan_user_id', 'plan', type_='foreignkey') # Используем явное имя

    # Удаляем колонку
    op.drop_column('plan', 'user_id')

    # ### end Alembic commands ###