"""empty message

Revision ID: 9e86275a5c3a
Revises: c8ffa34f572b
Create Date: 2025-04-16 16:54:37.479710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e86275a5c3a'
down_revision = 'c8ffa34f572b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'publication_type_display_name', ['display_name_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('display_name_id')

    # ### end Alembic commands ###
