"""Make type_id nullable and add ondelete=SET NULL in Publication and PlanEntry

Revision ID: b5849e7f2318
Revises: fd1156d3c5f5
Create Date: 2025-04-18 16:34:18.153037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5849e7f2318'
down_revision = 'fd1156d3c5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.drop_constraint('plan_entry_type_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publication_type', ['type_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.alter_column('type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('publication_type_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publication_type', ['type_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('publication_type_id_fkey', 'publication_type', ['type_id'], ['id'])
        batch_op.alter_column('type_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('plan_entry_type_id_fkey', 'publication_type', ['type_id'], ['id'])

    # ### end Alembic commands ###
