"""Add detailed fields to Publication

Revision ID: b8ff6c629331
Revises: 203a78069fea
Create Date: 2025-04-20 13:19:06.838141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ff6c629331'
down_revision = '203a78069fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journal_conference_name', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('doi', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('issn', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('isbn', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('quartile', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('number_volume_pages', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('publisher_location', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('printed_sheets_volume', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('circulation', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('classification_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('classification_code')
        batch_op.drop_column('circulation')
        batch_op.drop_column('printed_sheets_volume')
        batch_op.drop_column('publisher_location')
        batch_op.drop_column('publisher')
        batch_op.drop_column('department')
        batch_op.drop_column('number_volume_pages')
        batch_op.drop_column('quartile')
        batch_op.drop_column('isbn')
        batch_op.drop_column('issn')
        batch_op.drop_column('doi')
        batch_op.drop_column('journal_conference_name')

    # ### end Alembic commands ###
