"""empty message

Revision ID: c8ffa34f572b
Revises: 2c364f1b2d23
Create Date: 2025-04-15 16:03:30.650400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ffa34f572b'
down_revision = '2c364f1b2d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_type_display_name', schema=None) as batch_op:
        batch_op.drop_constraint('publication_type_display_name_publication_type_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publication_type', ['publication_type_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_type_display_name', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('publication_type_display_name_publication_type_id_fkey', 'publication_type', ['publication_type_id'], ['id'])

    # ### end Alembic commands ###
