"""create initial tables

Revision ID: de94852c81d3
Revises: 
Create Date: 2026-02-16 21:42:15.230957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de94852c81d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_statuses_id'), 'plan_statuses', ['id'], unique=False)
    op.create_table('publication_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_statuses_title'), 'publication_statuses', ['title'], unique=True)
    op.create_table('publication_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_types_title'), 'publication_types', ['title'], unique=True)
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishers_id'), 'publishers', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('university_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_department_id'), 'university_department', ['id'], unique=False)
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('middle_name', sa.String(length=255), nullable=False),
    sa.Column('third_name', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['university_department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ISSN', sa.String(length=256), nullable=True),
    sa.Column('ISBN', sa.String(length=256), nullable=True),
    sa.Column('volume', sa.String(length=24), nullable=True),
    sa.Column('quartile', sa.String(length=120), nullable=True),
    sa.Column('issue', sa.String(length=24), nullable=True),
    sa.Column('circulation', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journals_id'), 'journals', ['id'], unique=False)
    op.create_table('publication_type_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_type_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['publication_type_id'], ['publication_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_type_aliases_alias'), 'publication_type_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_publication_type_aliases_publication_type_id'), 'publication_type_aliases', ['publication_type_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['plan_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=36), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('internal_url', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=512), nullable=True),
    sa.Column('printed_sheets_volume', sa.Float(), nullable=True),
    sa.Column('classification_code', sa.String(length=55), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('work_form', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('type_alias_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['publication_statuses.id'], ),
    sa.ForeignKeyConstraint(['type_alias_id'], ['publication_type_aliases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_id'), 'publications', ['id'], unique=False)
    op.create_table('author_publication',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('author_id', 'publication_id')
    )
    op.create_table('journal_publications',
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('journal_id', 'publication_id')
    )
    op.create_table('plan_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_comments_id'), 'plan_comments', ['id'], unique=False)
    op.create_table('plan_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_amount_planned', sa.Integer(), nullable=False),
    sa.Column('type_alias_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['type_alias_id'], ['publication_type_aliases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_entries_id'), 'plan_entries', ['id'], unique=False)
    op.create_table('plan_entry_publications',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('plan_entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_entry_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('publication_id', 'plan_entry_id')
    )
    op.create_table('plan_status_temp',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['plan_statuses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('plan_id', 'status_id')
    )
    op.create_table('publication_status_temp',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['publication_statuses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('publication_id', 'status_id')
    )
    op.create_table('publication_tags',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('publication_id', 'tag_id')
    )
    op.create_table('publication_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('status_change_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.ForeignKeyConstraint(['status_change_id'], ['publication_status_temp.publication_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_change_id')
    )
    op.create_index(op.f('ix_publication_comments_id'), 'publication_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_comments_id'), table_name='publication_comments')
    op.drop_table('publication_comments')
    op.drop_table('publication_tags')
    op.drop_table('publication_status_temp')
    op.drop_table('plan_status_temp')
    op.drop_table('plan_entry_publications')
    op.drop_index(op.f('ix_plan_entries_id'), table_name='plan_entries')
    op.drop_table('plan_entries')
    op.drop_index(op.f('ix_plan_comments_id'), table_name='plan_comments')
    op.drop_table('plan_comments')
    op.drop_table('journal_publications')
    op.drop_table('author_publication')
    op.drop_index(op.f('ix_publications_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_publication_type_aliases_publication_type_id'), table_name='publication_type_aliases')
    op.drop_index(op.f('ix_publication_type_aliases_alias'), table_name='publication_type_aliases')
    op.drop_table('publication_type_aliases')
    op.drop_index(op.f('ix_journals_id'), table_name='journals')
    op.drop_table('journals')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_table('authors')
    op.drop_index(op.f('ix_university_department_id'), table_name='university_department')
    op.drop_table('university_department')
    op.drop_table('tags')
    op.drop_index(op.f('ix_publishers_id'), table_name='publishers')
    op.drop_table('publishers')
    op.drop_index(op.f('ix_publication_types_title'), table_name='publication_types')
    op.drop_table('publication_types')
    op.drop_index(op.f('ix_publication_statuses_title'), table_name='publication_statuses')
    op.drop_table('publication_statuses')
    op.drop_index(op.f('ix_plan_statuses_id'), table_name='plan_statuses')
    op.drop_table('plan_statuses')
    # ### end Alembic commands ###
