"""Add publication_url to Publication model

Revision ID: e27d32e71660
Revises: a1fe8eeb8772
Create Date: 2025-06-10 15:32:18.631316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27d32e71660'
down_revision = 'a1fe8eeb8772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_url', sa.Text(), nullable=True))

    with op.batch_alter_table('publication_field_hint', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['field_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_field_hint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('publication_url')

    # ### end Alembic commands ###
