"""Add is_locked to PlanEntry

Revision ID: edea0a8d2c39
Revises: bc7fd4311d19
Create Date: 2025-03-07 01:28:23.095887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edea0a8d2c39'
down_revision = 'bc7fd4311d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.drop_column('is_locked')

    # ### end Alembic commands ###
