"""Add ondelete=SET NULL to display_name_id in Publication and PlanEntry

Revision ID: fd1156d3c5f5
Revises: 9e86275a5c3a
Create Date: 2025-04-18 16:26:59.689762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1156d3c5f5'
down_revision = '9e86275a5c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.drop_constraint('plan_entry_display_name_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publication_type_display_name', ['display_name_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_constraint('publication_display_name_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publication_type_display_name', ['display_name_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('publication_display_name_id_fkey', 'publication_type_display_name', ['display_name_id'], ['id'])

    with op.batch_alter_table('plan_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('plan_entry_display_name_id_fkey', 'publication_type_display_name', ['display_name_id'], ['id'])

    # ### end Alembic commands ###
